### ISSUE TITLE
Permettre de mettre à jour les listes sans rebuild l'appli web

### ISSUE THREAD

**Issue by mkalam-alami** [supercinemarbre/supercinemarbre.github.io#40]

**Comment by 520-STB** [comment]
Hello,
En theorie, si je clone cette repo, que je recupere les token API et que je suit ta doc pour mettre a jour les liste des episodes tout seul comme un grand.
Est-ce que je pourrai juste faire une PR de la liste a jour, pour mettre le site a jour ?
(Ce qui te permettrai de juste avoir a valider ma PR)

**Comment by mkalam-alami** [comment]
C'est ça, au détail près qu'il y a souvent une ou deux références IMDB qui sont mal détectées, dans ces cas il faut [modifier un fichier JSON](https://github.com/supercinemarbre/supercinemarbre.github.io/blob/master/importer/data/scb_patch.json) puis relancer l'import.

Je viens de faire une petite passe pour mettre à jour le readme, si tu veux faire l'essai la prochaine fois y'a normalement toutes les bonnes infos maintenant !

**Comment by 520-STB** [comment]
Merci ! L'épisode 129 est sorti, je ferai l'essai des que j'aurai mis a jour les timestamps.
