### ISSUE TITLE
Ajout des episodes 130,131 et 132

### ISSUE THREAD

**Issue by 520-STB** [supercinemarbre/supercinemarbre.github.io#41]
Hello,

J'ai rattrapé mon retard. 
Par contre, désolé, je n'ai pas retenté de mettre a jour la liste moi meme. J'avais des soucis avec le package cheerio il me semble, il faudrait que creuse encore le sujet.

**Comment by mkalam-alami** [comment]
Je viens de mettre à jour les dépendances, ça m'a fait faire 2-3 modifs en rapport avec ce package c'est peut-être lié. Tu peux essayer de mettre à jour les sources puis refaire un `npm install` à l'occasion.

IMDB a pas trop aimé cette fournée de films donc y'a eu pas mal de retouches manuelles, c'est pas plus mal au final ça nous a réparti le boulot :)

Merci
