### ISSUE TITLE
Licences : mentionner TMDB et JustWatch comme sources

### ISSUE THREAD

**Issue by mkalam-alami** [supercinemarbre/supercinemarbre.github.io#50]

**Comment by 520-STB** [comment]
D'après les [Terms of Use](https://www.themoviedb.org/terms-of-use) de  TMDB:

```
3. Attribution
- You shall use the TMDb logo to identify your use of the TMDb APIs.
- You shall place the following notice prominently on your application: "This product uses the TMDb API but is not endorsed or certified by TMDb."
- Any use of the TMDb logo in your application shall be less prominent than the logo or mark that primarily describes the application and your use of the TMDb logo shall not imply any endorsement by TMDb.
```

**Comment by mkalam-alami** [comment]
Merci. Je me suis dit la même chose pour Justwatch, je pense pas qu'ils se plaindraient des liens :)

**Comment by 520-STB** [comment]
@mkalam-alami Bizarrement, la mention de TMDB n'apparaît pas. Pas de problème dans mon env local.

**Comment by mkalam-alami** [comment]
Ah j'avais oublié de faire un build

**Comment by 520-STB** [comment]
Ok, tu as une action manuelle de ton côté. Je pensais que le deploy était automatique.

**Comment by mkalam-alami** [comment]
En fait si on fait des modifs dans les fichiers de l'application web (.vue / .ts / .scss) il faut faire un `npm run build` pour que ça transforme le tout en du javascript tout prêt dans le dossier `docs`. En cas d'oubli il peut y avoir un décalage entre ce qui est déployé (dossier docs) et les sources (dossier webapp).
