### ISSUE TITLE
Dans la vue par épisode, la décénnie n'apparaît pas toujours

### ISSUE THREAD

**Issue by 520-STB** [supercinemarbre/supercinemarbre.github.io#54]
Par exemple, episode 139, 136, 131 ...

**Comment by 520-STB** [comment]
Correction manuelle de la décade manquante pour certains épisodes (2c9a910dca41733eed3eb0e44705c225d19e6a1c)
La détection de la décénie de l'épisode n'est pas infaillible, et elle ne fonctionne pas pour les épisodes "Devoir de vacances"

**Comment by mkalam-alami** [comment]
C'est perfectible oui, aujourd'hui pour qu'une décennie soit bien détectée il faut que TOUS les films de l'épisode soient raccord niveau décennie, s'il y a des données manquantes [ça a l'air de de rien mettre](
https://github.com/supercinemarbre/supercinemarbre.github.io/blob/2c9a910dca41733eed3eb0e44705c225d19e6a1c/importer/src/scb.ts#L77). Ca doit s'assouplir facilement.

(Note : à vérifier aussi si la donnée peut se rectifier après coup en cas d'erreur de détection de film)

**Comment by mkalam-alami** [comment]
Règle assouplie pour mettre par défaut la décennie majoritaire de l'épisode
