### ISSUE TITLE
Les liens pour écouter l'épisode 9 sont cassés

### ISSUE THREAD

**Issue by mkalam-alami** [supercinemarbre/supercinemarbre.github.io#56]
C'est peut-être lié à l'accent dans le titre, si c'est ça y'en a peut-être d'autres avec le même souci.

**Comment by 520-STB** [comment]
Vu sur le Discord, les url de tous les épisodes avec un accent ont été modifiée.
Il y a 29 épisodes à corriger apparement.
- [ ] identifier les 29 épisodes concernés (9, 100 ...)
- [ ] search & replaces dans tous les fichers concernés
- [ ] déploiement (git push)

**Comment by mkalam-alami** [comment]
J'ai relancé de zéro une synchro des épisodes, donc on devrait être pas trop mal, à confirmer

**Comment by 520-STB** [comment]
Ca à l'air bien, j'ai voulu écouté la critique de "It follows" (episode 100) ce matin,  ca ne fonctionnait plus.
Je viens de le refaire et ça fonctionne à nouveau, au moins pour cet épisode, bravo!

**Comment by mkalam-alami** [comment]
Je considère que c'est corrigé, à réouvrir si besoin
