### ISSUE TITLE
episode 160 introuvable

### ISSUE THREAD

**Issue by 520-STB** [supercinemarbre/supercinemarbre.github.io#57]
J'ai saisi a la main l'épisode 160 dans scb_episodes.json. Faute d'avoir su amélioré le script d'import.

La fonction scrapeScbEpisode() ne trouve pas l'épisode 160. Il me semble que c'est parce que le titre de l'épisode contient un espace supplémentaire avant ':', mais je n'en suis pas sûr.

**Comment by mkalam-alami** [comment]
Bien reçu je jetterai un oeil

**Comment by stephane-bellis** [comment]
Je peux revenir dessus eventuellement. En fait, la fontion download qui est utilisée ici, je n'ai pas trouvé s documentation, c'est du nodejs natif ou c'est un module externe ?

**Comment by 520-STB** [comment]
En fait, Je n'ai pas trouvé la documentation de la fonction download() qui est utilisée dans scrapeScbEpisode().
C'est natif nodejs ou c'est un module externe ?

**Comment by mkalam-alami** [comment]
C'est [un package][https://www.npmjs.com/package/download) effectivement

**Comment by mkalam-alami** [comment]
Le problème de détection vient du fait qu'il y a un double espace dans le titre de l'article (entre 160 et les deux points). J'ai assoupli un peu la détection de titre pour corriger ça.

Traité via b9dbedb

**Comment by mkalam-alami** [comment]
Merci au passage pour tes mises à jour toujours aussi régulières c'est top !

**Comment by 520-STB** [comment]
De rien, je suis bien rodé maintenant. Çà me fait plaisirs de maintenir le contenu et c'est pas bien compliqué, tu as fait du bon travail.

En fait si je passais moins de temps à jouer aux jeux-videos et à regarder les films recommandés par le RPU, j'aurai du temps dispo pour dev sur ce projet. Parce que mon diagnostique était le bon sur cette issue, mais il aurait fallu que je passe plus de temps à me documenter et chercher la solution, bien joué.
